### ISSUE TITLE
Interested in any of these as PRs?

### ISSUE THREAD

**Issue by stevencorona** [handlecommerce/liquex#35]
Hi Mark,

Thanks for the library. It has been really useful and I'm currently using it to drive end-user definable templates in a project of mine. I've developed several large bits of functionality and I'm curious if you'd be interested in PRs to bring any of them into the core library. They are:

1. An implementation of the Shopify `render` tag to handle nested rendering (depends on the caller to provide a loader function).

2. A rendering budget / reduction limit - basically tracks the number of reductions and raises if it's exceeded. Needed this to prevent accidentally creating render tag cycles, but could be applied to the entire render loop.

3. An implementation of `Phoenix.Template.Engine` that supports storing the liquid templates in the `template` folder and parses them at compile time - generating a function per template similar to how eex templates work. In my project, I use this to make the "default" system templates part of my normal workflow, while allowing the end-user to override them with their own liquid (albeit slower because they aren't pre-parsed).

4. I'm currently using the liquid templates in a LiveView project, and they actually work really well! The only negative is that you lose diff tracking once you enter the liquid template, and also can't render any live_components. The liquid AST is actually conceptually mostly maps to the `Phoenix.LiveView.Rendered` struct, which is necessary to get full diff tracking, so I'm working on a way to transform the AST.

Would you be interested in having me contributing any of these back? 3 and 4 sorta ride the line of maybe being a separate library.

**Comment by markglenn** [comment]
Thank you for the interest. I'm always open to PRs.

Let me answer your questions one at a time.

1. We currently have this library running on our site called Enology. In that, I include additional functionality outside of the base functionality of the Liquid gem. I feel like this library needs to be a "pure" implementation of Liquid with the express design of being easy to extend. That being said, I think there's a real need to have these extension tags somewhere instead of reinventing the wheel. I was thinking of a secondary extension library, possibly called Liquex.Ext.

2. We again have this in Enology, but it never made it back into the base library. Our implementation is very naive and checks nesting levels, but not complexity of tags. I'm open to any pull requests for this since I don't think our current implementation is good enough. This is one feature I think we're lacking right now.

3. I've had no personal need for adding a template engine for Phoenix since our site dynamically renders everything from cache or the database. I'm open to ideas here, but not sure how much use there is outside of a niche. Other templating libraries are much more capable, and Liquid is really useful when it comes to rendering content from users or external sources. Also, I'm trying really hard not to depend on Phoenix at all in this project. However, if you wanted to add this, I'm more than willing to link to a separate library within the documentation because I can see it being useful to some.

4. This is an interesting idea. Again, I'm trying not to depend on Phoenix and trying to keep the library as closely matching the Liquid gem as possible. I haven't looked deep enough into LiveView's internals to know how to support this.

**Comment by markglenn** [comment]
After writing this response, I see that `render` is now included in the base library. I'm open to getting this included.

**Comment by markglenn** [comment]
The render tag has been added within #37. I still need to document how to use it, but it matches the full implementation of the Shopify gem and is fully usable.
